@startuml

actor User
participant "App" as App
box EHR
    participant  "EHR\nFHIR" as EhrFHIR
    participant  "EHR\nAS" as EhrAS
end box
box Other
    participant  "Other\nFHIR" as OtherFHIR
    participant  "Other\nAS" as OtherAS
end box
participant  "Brand\nProvider" as BrandProvider

=== Access EHR content ==
App -> EhrFHIR: GET content [ehr-access-token]

=== Access Other content ==
App -> OtherFHIR: GET content [other-access-token]

@enduml