@startuml

actor User
participant "App" as App
box EHR
    participant  "EHR\nFHIR" as EhrFHIR
    participant  "EHR\nAS" as EhrAS
end box
box Other
    participant  "Other\nFHIR" as OtherFHIR
    participant  "Other\nAS" as OtherAS
end box
participant  "Brand\nProvider" as BrandProvider

=== Request Other Access token ==
App -> OtherAS ++: retrieve-token( <open-id-token> )
note right
    clientId: <other-clientid>
    grant_type = urn:ietf:params:oauth:grant-type:token-exchange
    subject_token = <open-id-token>
    subject_token_type= urn:ietf:params:oauth:token-type:id_token
end note
OtherAS ->  EhrAS ++: introspect <open-id-token> [backend-token]
OtherAS <-- EhrAS --
note right: <patient-id> <user>
OtherAS -> EhrAS: GET patient [backend-token]
OtherAS -> EhrAS: GET user [backend-token]
OtherAS -> OtherAS: determine scopes
App <-- OtherAS --: <other-token-response>
note left
    token-response:
        <other-access-token>
end note

@enduml